---
title: "Synthèse"
---

# Que peut-on retenir de cette enquête ? {.tabset}

<br>

## Enjeux selon les enquêtés

::: {align="justify"}
Pour cette question des principaux enjeux, on retrouve deux situations assez distinctes entre les deux terrains d'enquête. D'une part, si l'on se focalise sur la première réponse choisie par les enquêtés, les EPT du Grand Paris sont tous préoccupés en majorité par la situation sanitaire. A Londres, quelques Boroughs présentent d'autres réponses comme la criminalité ou le coût de la vie. D'autre part, pour la 2ème réponse la plus choisie, la Métropole du Grand Paris présente une situation très hétérogène (8 réponses différentes pour 13 objets géographiques) alors que Londres montre plus d'homogénéité sur son territoire. Il est également important que seuls le logement et la criminalité sont communs aux deux espaces d'études.
:::

## La vie dans son quartier pendant la Covid

::: {align="justify"}
Dans les 2 cas la question de l'hyperproximité est importante (90% environ en moyenne de l'ensemble des répondants), on retrouve alors une certaine homogonéité, avec des résultats proches de ces 90% pour l'ensemble des objets géographiques quelque soit le terrain d'étude.
:::

## Quitter les grandes villes après la Covid ?

::: {align="justify"}
Trouver citation sur exode urbain / départ des métropoles
:::

## Immigration 

::: {align="justify"}
Londres dans sa généralité = environ 2 fois plus content de l'immigration venant de l'étranger que Paris (61% contre 37%

Londres 25% pour plus d'immigration contre 15% pour Paris : à noter la différence d'échelle, la question porte sur l'ensemble de Londres du côté britannique mais uniquement sur la commune du côté français. ==\> Plus proche de son cadre de vie direct = pas envie de "changements".
:::

## Sécurité

::: {align="justify"}
Répondants des 2 espaces d'études se sentent en sécurité dans leur quartier (84% pour Paris et 88% pour Londres). A Londres : très homogène, tous proche de la moyenne, alors qu'à Paris 1 EPT se sent moins en sécurité : Plaine Commune.

La nuit, les gens se sentent moins en sécurité dans les deux cas, on descend a 52% à Paris et 58% à Londres. = Davantage de rouge sur la carte "se sentir en sécurité". Opposition ouest-reste de la MGP . Londres, l'ouest se sent moins en sécurité qu'une partie de l'*Inner London* ou de l'est.
:::

## Logement, travail et vie de famille

::: {align="justify"}
<https://www.bloomberg.com/opinion/articles/2021-10-19/covid-didn-t-make-the-dream-of-cheaper-london-paris-come-true#xj4y7vzkg>

Article met l'accent sur le fait que les métropoles mondiales restent des espaces pour les riches, et donc que ces derniers s'adaptent au mieux aux différents enjeux contemporains, comme la crise du logement auquel font face les métropoles qui n'ont pas vu les prix de l'immobilier diminuer après les prémices de la crise sanitaire.

Dans les 2 cas : majorité des gens pensent que se loger n'est pas abordable pour les gens comme eux. Sentiment renforcé dans la Vile de Paris alors que la situation de l'*Inner London* est

L'accès à la propriété est également trop cher pour près de 3/4 des répondants dans les deux cas, la MGP étant un pêu plus optimiste et présentant des EPT aux résultats proches, tout comme Londres où l'ensemble du territoire est assez homogène sur cette question.

Pour ce qui est du télétravail, on peut davantage télétravailler à Londres (54%) qu'à Paris (40%). Spatialement, on retrouve une opposition *inner-London / outer-London* assez marquée, avec quelques exceptions. Et pour Paris, une opposition Centre & ouest *versus* le reste du territoire d'enquête, avec principalement le Nord qui présente également une grande part de réponse "ne peut pas travailler".

Le "comme moi" joue pour beaucoup dans la formation des résultats pour ces deux questions, sans vraiment connaître le profil de chaque répondant il est difficile d'apporter des éléments d'interprétation à ces résultats. (est-ce en fonction de l'âge ? du genre ? de la CSP ?)
:::

## Rebondir après la pandémie

::: {align="justify"}
Renvoie à l'optimisme général / de chaque objet géographique
:::

## Des conclusions à l'étude ?

::: {align="justify"}
La première chose à préciser est que la prise en main de l'enquête a été compliquée, notamment du fait qu'elle n'avait pas vocation à être spatialisée. Le travail effectué a alors montré qu'il fallait davantage apporté une spatialité aux enquêtes pour pouvoir observer localement les résultats (pas seulement centre et banlieue). De plus le fait que pour Paris, les arrondissements ont été mis de côté fait qu'on se retrouve avec une masse de répondants (500) pour cet objet géographique, qu'on ne retrouve pas sur les autres (moins de 20).

Un autre point à mettre en avant est la différence d'échelle entre les deux terrains d'enquête. En effet, si certaines questions portaient sur le quartier du répondant dans les deux cas, d'autres questions traitaient de la commune pour le Grand Paris, et de Londres dans sa globalité pour Londres. Il est donc difficile de comparer les deux territoires dans ces cas là, malgré une réagrégation avec des mailles relativement similaires géographiquement parlant.

De plus, dans les deux cas d'études, on ne peut pas observer une réelle géographie des résultats de l'enquête, certaines questions en présentent une comme un effet centre-périphérie par exemple, mais il s'agit là d'exceptions, la majorité des questions n'offrent en effet pas de résultats spatialement interprétables (il faudrait prendre en compte tous les aspects de chaque territoire pour comprendre pourquoi on obtient ces résultats).
:::
